// import { ForecastEntry } from "@/utils/interfaces";

async function fetchData(endpoint?: string) {
  const url = `${process.env.RAPID_URL}${endpoint ? endpoint : ""}`;

  const options: RequestInit = {
    cache: "force-cache",
    headers: {
      "x-rapidapi-key": `${process.env.RAPID_KEY}`,
      "x-rapidapi-host": `${process.env.RAPID_HOST}`,
    },
  };

  const results = await fetch(url, options);

  return await results.json();
}

export async function nearestPlace(coords: string) {
  return await fetchData(`nearest_place?${coords}`);
}

export async function findPlaces(searchQuery: string) {
  return await fetchData(`find_places_prefix?text=${searchQuery}`);
}

export async function fetchCurrentWeather(place_id: string) {
  return await fetchData(`current?place_id=${place_id}`);
}

export const forecastData = {
  lat: "54.68916N",
  lon: "25.2798E",
  elevation: 98,
  timezone: "Europe/Vilnius",
  units: "metric",
  hourly: {
    data: [
      {
        date: "2026-03-23T19:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 10.2,
        feels_like: 7.5,
        wind_chill: 9,
        dew_point: 3,
        wind: { speed: 1.6, gusts: 1.8, dir: "W", angle: 265 },
        cloud_cover: 96,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 353.22,
        uv_index: 0,
        humidity: 60,
        visibility: 24.14,
      },
      {
        date: "2026-03-23T20:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9,
        feels_like: 6,
        wind_chill: 8,
        dew_point: 2.5,
        wind: { speed: 1.7, gusts: 1.7, dir: "W", angle: 263 },
        cloud_cover: 92,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 2 },
        ozone: 351.55,
        uv_index: 0,
        humidity: 63,
        visibility: 24.14,
      },
      {
        date: "2026-03-23T21:00:00",
        weather: "cloudy",
        icon: 30,
        summary: "Cloudy",
        temperature: 7.5,
        feels_like: 5,
        wind_chill: 6.5,
        dew_point: 1,
        wind: { speed: 1.6, gusts: 1.7, dir: "SW", angle: 236 },
        cloud_cover: 84,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 10 },
        ozone: 350.2,
        uv_index: 0,
        humidity: 63,
        visibility: 24.13,
      },
      {
        date: "2026-03-23T22:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 6.8,
        feels_like: 5,
        wind_chill: 5,
        dew_point: 0.8,
        wind: { speed: 1.9, gusts: 1.8, dir: "SW", angle: 223 },
        cloud_cover: 69,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 15 },
        ozone: 351.93,
        uv_index: 0,
        humidity: 65,
        visibility: 24.14,
      },
      {
        date: "2026-03-23T23:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 6,
        feels_like: 5,
        wind_chill: 4,
        dew_point: 0.8,
        wind: { speed: 2.1, gusts: 1.9, dir: "SW", angle: 223 },
        cloud_cover: 28,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 25 },
        ozone: 352.16,
        uv_index: 0,
        humidity: 69,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T00:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 5.5,
        feels_like: 4.2,
        wind_chill: 3.2,
        dew_point: 0.5,
        wind: { speed: 2.3, gusts: 1.9, dir: "SW", angle: 220 },
        cloud_cover: 47,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 26 },
        ozone: 352.3,
        uv_index: 0,
        humidity: 70,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T01:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 4.8,
        feels_like: 3.5,
        wind_chill: 2.5,
        dew_point: 0.8,
        wind: { speed: 2.4, gusts: 2.6, dir: "SW", angle: 220 },
        cloud_cover: 32,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 32 },
        ozone: 356.11,
        uv_index: 0,
        humidity: 75,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T02:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 4.2,
        feels_like: 3,
        wind_chill: 2,
        dew_point: 0.5,
        wind: { speed: 2.4, gusts: 3.1, dir: "SW", angle: 223 },
        cloud_cover: 26,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 35 },
        ozone: 361.04,
        uv_index: 0,
        humidity: 76,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T03:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 3.5,
        feels_like: 2,
        wind_chill: 1,
        dew_point: -0.2,
        wind: { speed: 2.4, gusts: 2.8, dir: "SW", angle: 226 },
        cloud_cover: 24,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 38 },
        ozone: 371.16,
        uv_index: 0,
        humidity: 76,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T04:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 3.5,
        feels_like: 2.2,
        wind_chill: 1.2,
        dew_point: -0.2,
        wind: { speed: 2.3, gusts: 2.5, dir: "SW", angle: 228 },
        cloud_cover: 24,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 39 },
        ozone: 380.93,
        uv_index: 0,
        humidity: 76,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T05:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 3,
        feels_like: 1.5,
        wind_chill: 0.5,
        dew_point: -0.5,
        wind: { speed: 2.3, gusts: 2.5, dir: "SW", angle: 218 },
        cloud_cover: 65,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 38 },
        ozone: 380.17,
        uv_index: 0,
        humidity: 77,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T06:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 2.8,
        feels_like: -0.2,
        wind_chill: 0.2,
        dew_point: -0.5,
        wind: { speed: 2.4, gusts: 2.6, dir: "SW", angle: 218 },
        cloud_cover: 60,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 40 },
        ozone: 378.29,
        uv_index: 0,
        humidity: 79,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T07:00:00",
        weather: "cloudy",
        icon: 6,
        summary: "Cloudy",
        temperature: 2.8,
        feels_like: -0.8,
        wind_chill: 0.2,
        dew_point: -0.8,
        wind: { speed: 2.3, gusts: 3.1, dir: "SW", angle: 217 },
        cloud_cover: 83,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 38 },
        ozone: 376.09,
        uv_index: 0.1,
        humidity: 77,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T08:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 4.2,
        feels_like: 1,
        wind_chill: 2,
        dew_point: 0.2,
        wind: { speed: 2.2, gusts: 3.7, dir: "SW", angle: 216 },
        cloud_cover: 74,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 30 },
        ozone: 378.19,
        uv_index: 0.34,
        humidity: 75,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T09:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 6.8,
        feels_like: 3.2,
        wind_chill: 4.2,
        dew_point: 1,
        wind: { speed: 2.7, gusts: 4.1, dir: "SW", angle: 222 },
        cloud_cover: 57,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 18 },
        ozone: 380.67,
        uv_index: 0.75,
        humidity: 66,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T10:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9,
        feels_like: 5.8,
        wind_chill: 6.8,
        dew_point: 2.5,
        wind: { speed: 3, gusts: 5.1, dir: "SW", angle: 226 },
        cloud_cover: 92,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 2 },
        ozone: 382.86,
        uv_index: 1.32,
        humidity: 63,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T11:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 10.8,
        feels_like: 7.2,
        wind_chill: 8.8,
        dew_point: 3.2,
        wind: { speed: 3.6, gusts: 5.8, dir: "SW", angle: 230 },
        cloud_cover: 99,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 383.03,
        uv_index: 1.53,
        humidity: 59,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T12:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11.8,
        feels_like: 8.2,
        wind_chill: 9.8,
        dew_point: 3.2,
        wind: { speed: 4, gusts: 7.2, dir: "SW", angle: 232 },
        cloud_cover: 97,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 382.47,
        uv_index: 1.98,
        humidity: 55,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T13:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.2,
        feels_like: 8,
        wind_chill: 10.5,
        dew_point: 2.8,
        wind: { speed: 4.5, gusts: 7.8, dir: "SW", angle: 236 },
        cloud_cover: 100,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 380.57,
        uv_index: 1.79,
        humidity: 52,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T14:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.5,
        feels_like: 8.2,
        wind_chill: 10.2,
        dew_point: 2.8,
        wind: { speed: 4.9, gusts: 8, dir: "WSW", angle: 242 },
        cloud_cover: 100,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 377.96,
        uv_index: 1.45,
        humidity: 51,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T15:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.5,
        feels_like: 8.2,
        wind_chill: 10.8,
        dew_point: 3.2,
        wind: { speed: 4.7, gusts: 8.1, dir: "WSW", angle: 243 },
        cloud_cover: 100,
        pressure: 1015,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 376.66,
        uv_index: 1.18,
        humidity: 53,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T16:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.5,
        feels_like: 8.8,
        wind_chill: 10.8,
        dew_point: 3.5,
        wind: { speed: 4.3, gusts: 7.9, dir: "WSW", angle: 240 },
        cloud_cover: 100,
        pressure: 1015,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 380.12,
        uv_index: 0.58,
        humidity: 54,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T17:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11.8,
        feels_like: 7.8,
        wind_chill: 9.8,
        dew_point: 3.5,
        wind: { speed: 3.9, gusts: 7.5, dir: "WSW", angle: 236 },
        cloud_cover: 100,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 380.93,
        uv_index: 0.29,
        humidity: 56,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T18:00:00",
        weather: "cloudy",
        icon: 6,
        summary: "Cloudy",
        temperature: 10.5,
        feels_like: 7.2,
        wind_chill: 9.2,
        dew_point: 4,
        wind: { speed: 3.3, gusts: 7.3, dir: "SW", angle: 229 },
        cloud_cover: 88,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 380.44,
        uv_index: 0,
        humidity: 64,
        visibility: 24.14,
      },
      {
        date: "2026-03-24T19:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 8.5,
        feels_like: 5.5,
        wind_chill: 6.5,
        dew_point: 3.2,
        wind: { speed: 2.9, gusts: 5.9, dir: "SW", angle: 218 },
        cloud_cover: 92,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 5 },
        ozone: 379.32,
        uv_index: 0,
        humidity: 69,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T20:00:00",
        weather: "cloudy",
        icon: 30,
        summary: "Cloudy",
        temperature: 7.2,
        feels_like: 4,
        wind_chill: 5.5,
        dew_point: 2.8,
        wind: { speed: 3, gusts: 4.9, dir: "SSW", angle: 211 },
        cloud_cover: 86,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 12 },
        ozone: 379.69,
        uv_index: 0,
        humidity: 73,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T21:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 6.8,
        feels_like: 3.8,
        wind_chill: 4.2,
        dew_point: 3,
        wind: { speed: 3, gusts: 4.9, dir: "SSW", angle: 206 },
        cloud_cover: 65,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 17 },
        ozone: 378.88,
        uv_index: 0,
        humidity: 76,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T22:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 5.8,
        feels_like: 2.8,
        wind_chill: 3.2,
        dew_point: 2,
        wind: { speed: 3.2, gusts: 5.7, dir: "SSW", angle: 202 },
        cloud_cover: 77,
        pressure: 1013,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 21 },
        ozone: 378.46,
        uv_index: 0,
        humidity: 76,
        visibility: 24.13,
      },
      {
        date: "2026-03-24T23:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5.2,
        feels_like: 1.5,
        wind_chill: 2.5,
        dew_point: 1.2,
        wind: { speed: 3.4, gusts: 6.2, dir: "SSW", angle: 205 },
        cloud_cover: 92,
        pressure: 1013,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 21 },
        ozone: 378.93,
        uv_index: 0,
        humidity: 75,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T00:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 5.2,
        feels_like: 2.8,
        wind_chill: 2.2,
        dew_point: 1.8,
        wind: { speed: 3.6, gusts: 6.9, dir: "SSW", angle: 202 },
        cloud_cover: 79,
        pressure: 1012,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 24 },
        ozone: 381.99,
        uv_index: 0,
        humidity: 78,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T01:00:00",
        weather: "cloudy",
        icon: 30,
        summary: "Cloudy",
        temperature: 5.5,
        feels_like: 2.5,
        wind_chill: 2.5,
        dew_point: 2.2,
        wind: { speed: 3.7, gusts: 7, dir: "SSW", angle: 201 },
        cloud_cover: 83,
        pressure: 1012,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 22 },
        ozone: 384.11,
        uv_index: 0,
        humidity: 79,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T02:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 5.5,
        feels_like: 1.5,
        wind_chill: 2.5,
        dew_point: 2.2,
        wind: { speed: 3.8, gusts: 7.4, dir: "SSW", angle: 198 },
        cloud_cover: 76,
        pressure: 1011,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 23 },
        ozone: 384.28,
        uv_index: 0,
        humidity: 79,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T03:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5.2,
        feels_like: 1.2,
        wind_chill: 2.2,
        dew_point: 1.8,
        wind: { speed: 3.9, gusts: 8, dir: "SSW", angle: 196 },
        cloud_cover: 92,
        pressure: 1011,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 21 },
        ozone: 383.43,
        uv_index: 0,
        humidity: 78,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T04:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5,
        feels_like: 1.2,
        wind_chill: 1.8,
        dew_point: 1.8,
        wind: { speed: 3.8, gusts: 8.5, dir: "SSW", angle: 194 },
        cloud_cover: 96,
        pressure: 1010,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 24 },
        ozone: 381.5,
        uv_index: 0,
        humidity: 79,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T05:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 4.8,
        feels_like: 1,
        wind_chill: 1.5,
        dew_point: 1.5,
        wind: { speed: 3.9, gusts: 9.2, dir: "SSW", angle: 192 },
        cloud_cover: 90,
        pressure: 1009,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 26 },
        ozone: 381.1,
        uv_index: 0,
        humidity: 79,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T06:00:00",
        weather: "cloudy",
        icon: 6,
        summary: "Cloudy",
        temperature: 4.8,
        feels_like: 1,
        wind_chill: 1.5,
        dew_point: 1.5,
        wind: { speed: 4.2, gusts: 9.1, dir: "S", angle: 190 },
        cloud_cover: 84,
        pressure: 1009,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 26 },
        ozone: 380.1,
        uv_index: 0,
        humidity: 79,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T07:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5,
        feels_like: 0.5,
        wind_chill: 1.5,
        dew_point: 1.2,
        wind: { speed: 4.7, gusts: 9.5, dir: "S", angle: 188 },
        cloud_cover: 100,
        pressure: 1008,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 23 },
        ozone: 379.86,
        uv_index: 0.1,
        humidity: 76,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T08:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 6,
        feels_like: 1.8,
        wind_chill: 2.8,
        dew_point: 1.8,
        wind: { speed: 5.2, gusts: 10.1, dir: "S", angle: 188 },
        cloud_cover: 100,
        pressure: 1007,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 18 },
        ozone: 380.73,
        uv_index: 0.32,
        humidity: 74,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T09:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7.5,
        feels_like: 2.8,
        wind_chill: 4.2,
        dew_point: 2.2,
        wind: { speed: 5.7, gusts: 11.1, dir: "S", angle: 189 },
        cloud_cover: 100,
        pressure: 1007,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 8 },
        ozone: 381.91,
        uv_index: 0.69,
        humidity: 69,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T10:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9.2,
        feels_like: 4,
        wind_chill: 6,
        dew_point: 2.5,
        wind: { speed: 6.3, gusts: 11.3, dir: "SSW", angle: 192 },
        cloud_cover: 100,
        pressure: 1006,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 382.14,
        uv_index: 1.15,
        humidity: 62,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T11:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11,
        feels_like: 5.5,
        wind_chill: 8,
        dew_point: 3.2,
        wind: { speed: 6.8, gusts: 11.7, dir: "S", angle: 191 },
        cloud_cover: 100,
        pressure: 1005,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 381.11,
        uv_index: 1.59,
        humidity: 58,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T12:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11.8,
        feels_like: 6.2,
        wind_chill: 8.8,
        dew_point: 2.8,
        wind: { speed: 7.5, gusts: 12.1, dir: "S", angle: 188 },
        cloud_cover: 93,
        pressure: 1004,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 2, storm: 0, freeze: 0 },
        ozone: 380.95,
        uv_index: 1.63,
        humidity: 54,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T13:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.2,
        feels_like: 6.5,
        wind_chill: 9.5,
        dew_point: 3,
        wind: { speed: 7.5, gusts: 12.1, dir: "S", angle: 187 },
        cloud_cover: 99,
        pressure: 1003,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 8, storm: 0, freeze: 0 },
        ozone: 379.28,
        uv_index: 1.34,
        humidity: 53,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T14:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.8,
        feels_like: 7,
        wind_chill: 10,
        dew_point: 3.2,
        wind: { speed: 7.4, gusts: 12, dir: "S", angle: 187 },
        cloud_cover: 100,
        pressure: 1002,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 8, storm: 0, freeze: 0 },
        ozone: 378.9,
        uv_index: 1.25,
        humidity: 52,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T15:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.8,
        feels_like: 6.8,
        wind_chill: 9.8,
        dew_point: 3,
        wind: { speed: 7.5, gusts: 11.9, dir: "S", angle: 185 },
        cloud_cover: 100,
        pressure: 1002,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 6, storm: 0, freeze: 0 },
        ozone: 378.52,
        uv_index: 1.01,
        humidity: 51,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T16:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.8,
        feels_like: 7.2,
        wind_chill: 10.2,
        dew_point: 3.5,
        wind: { speed: 7.2, gusts: 11.8, dir: "S", angle: 185 },
        cloud_cover: 100,
        pressure: 1001,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 379.15,
        uv_index: 0.53,
        humidity: 53,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T17:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 12.8,
        feels_like: 6.8,
        wind_chill: 9.8,
        dew_point: 3.8,
        wind: { speed: 7.1, gusts: 11.5, dir: "S", angle: 184 },
        cloud_cover: 98,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 377.34,
        uv_index: 0.22,
        humidity: 54,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T18:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11.8,
        feels_like: 6.2,
        wind_chill: 8.8,
        dew_point: 3,
        wind: { speed: 6.6, gusts: 11.3, dir: "S", angle: 181 },
        cloud_cover: 99,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 375.74,
        uv_index: 0,
        humidity: 54,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T19:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 11,
        feels_like: 5.5,
        wind_chill: 8,
        dew_point: 2.5,
        wind: { speed: 6.4, gusts: 10.9, dir: "S", angle: 178 },
        cloud_cover: 100,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 3, storm: 0, freeze: 0 },
        ozone: 373.38,
        uv_index: 0,
        humidity: 55,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T20:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 10.5,
        feels_like: 4.8,
        wind_chill: 7.2,
        dew_point: 2.2,
        wind: { speed: 6.5, gusts: 9.8, dir: "S", angle: 176 },
        cloud_cover: 100,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 373.43,
        uv_index: 0,
        humidity: 56,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T21:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 10.2,
        feels_like: 4.5,
        wind_chill: 6.5,
        dew_point: 2.2,
        wind: { speed: 6.7, gusts: 10.6, dir: "S", angle: 176 },
        cloud_cover: 100,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 374.89,
        uv_index: 0,
        humidity: 57,
        visibility: 24.14,
      },
      {
        date: "2026-03-25T22:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9.8,
        feels_like: 3.8,
        wind_chill: 6.2,
        dew_point: 1.8,
        wind: { speed: 6.5, gusts: 10.6, dir: "S", angle: 175 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 1, storm: 0, freeze: 0 },
        ozone: 376.82,
        uv_index: 0,
        humidity: 57,
        visibility: 24.13,
      },
      {
        date: "2026-03-25T23:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9.5,
        feels_like: 4,
        wind_chill: 6,
        dew_point: 2,
        wind: { speed: 6.4, gusts: 11.3, dir: "S", angle: 175 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 2, storm: 0, freeze: 0 },
        ozone: 379.93,
        uv_index: 0,
        humidity: 59,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T00:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 9.2,
        feels_like: 3.8,
        wind_chill: 5.8,
        dew_point: 2,
        wind: { speed: 6.2, gusts: 11.2, dir: "S", angle: 173 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 7, storm: 0, freeze: 0 },
        ozone: 384.09,
        uv_index: 0,
        humidity: 60,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T01:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 8.5,
        feels_like: 3,
        wind_chill: 5,
        dew_point: 1.5,
        wind: { speed: 6, gusts: 10.8, dir: "S", angle: 172 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 8, storm: 0, freeze: 4 },
        ozone: 388.9,
        uv_index: 0,
        humidity: 61,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T02:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 8,
        feels_like: 2.8,
        wind_chill: 4.8,
        dew_point: 1.5,
        wind: { speed: 5.5, gusts: 9.6, dir: "S", angle: 172 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 4, storm: 0, freeze: 7 },
        ozone: 393.61,
        uv_index: 0,
        humidity: 63,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T03:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7.2,
        feels_like: 2.8,
        wind_chill: 4.2,
        dew_point: 1.5,
        wind: { speed: 4.7, gusts: 8.5, dir: "S", angle: 184 },
        cloud_cover: 100,
        pressure: 999,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 6, storm: 0, freeze: 11 },
        ozone: 397,
        uv_index: 0,
        humidity: 66,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T04:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 6.8,
        feels_like: 2.5,
        wind_chill: 3.5,
        dew_point: 1.2,
        wind: { speed: 4.3, gusts: 7.8, dir: "S", angle: 183 },
        cloud_cover: 100,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 16, storm: 0, freeze: 14 },
        ozone: 400.14,
        uv_index: 0,
        humidity: 67,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T05:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 6.2,
        feels_like: 2.8,
        wind_chill: 3.8,
        dew_point: 2,
        wind: { speed: 3.4, gusts: 6.5, dir: "SSW", angle: 200 },
        cloud_cover: 100,
        pressure: 1000,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 20, storm: 0, freeze: 16 },
        ozone: 402.99,
        uv_index: 0,
        humidity: 74,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T06:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5.8,
        feels_like: 3.2,
        wind_chill: 4.2,
        dew_point: 2.2,
        wind: { speed: 2.4, gusts: 5.2, dir: "SW", angle: 230 },
        cloud_cover: 100,
        pressure: 1001,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 20, storm: 0, freeze: 19 },
        ozone: 404.21,
        uv_index: 0,
        humidity: 78,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T07:00:00",
        weather: "light_rain",
        icon: 10,
        summary: "Light rain",
        temperature: 5.8,
        feels_like: 3.5,
        wind_chill: 4.5,
        dew_point: 3.5,
        wind: { speed: 1.9, gusts: 3.9, dir: "W", angle: 272 },
        cloud_cover: 100,
        pressure: 1001,
        precipitation: { total: 0.4, type: "rain" },
        probability: { precipitation: 70, storm: 0, freeze: 19 },
        ozone: 405.37,
        uv_index: 0.01,
        humidity: 85,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T08:00:00",
        weather: "rain",
        icon: 11,
        summary: "Rain",
        temperature: 5.5,
        feels_like: 2.8,
        wind_chill: 3.8,
        dew_point: 4.2,
        wind: { speed: 2.3, gusts: 4.5, dir: "WNW", angle: 294 },
        cloud_cover: 100,
        pressure: 1002,
        precipitation: { total: 1.2, type: "rain" },
        probability: { precipitation: 95, storm: 0, freeze: 19 },
        ozone: 407.52,
        uv_index: 0.06,
        humidity: 91,
        visibility: 10.88,
      },
      {
        date: "2026-03-26T09:00:00",
        weather: "rain",
        icon: 11,
        summary: "Rain",
        temperature: 5.8,
        feels_like: 3.2,
        wind_chill: 4.2,
        dew_point: 4.5,
        wind: { speed: 1.6, gusts: 3.6, dir: "WNW", angle: 283 },
        cloud_cover: 100,
        pressure: 1003,
        precipitation: { total: 1.3, type: "rain" },
        probability: { precipitation: 95, storm: 0, freeze: 19 },
        ozone: 407.22,
        uv_index: 0.28,
        humidity: 91,
        visibility: 9.38,
      },
      {
        date: "2026-03-26T10:00:00",
        weather: "rain",
        icon: 11,
        summary: "Rain",
        temperature: 6.2,
        feels_like: 4,
        wind_chill: 5,
        dew_point: 5,
        wind: { speed: 1.6, gusts: 3.4, dir: "WSW", angle: 257 },
        cloud_cover: 100,
        pressure: 1003,
        precipitation: { total: 0.9, type: "rain" },
        probability: { precipitation: 95, storm: 0, freeze: 16 },
        ozone: 406.06,
        uv_index: 0.47,
        humidity: 91,
        visibility: 6.56,
      },
      {
        date: "2026-03-26T11:00:00",
        weather: "light_rain",
        icon: 10,
        summary: "Light rain",
        temperature: 6.5,
        feels_like: 4.5,
        wind_chill: 6,
        dew_point: 4.5,
        wind: { speed: 1.1, gusts: 2.9, dir: "WSW", angle: 245 },
        cloud_cover: 100,
        pressure: 1004,
        precipitation: { total: 0.3, type: "rain" },
        probability: { precipitation: 68, storm: 0, freeze: 15 },
        ozone: 405.51,
        uv_index: 0.51,
        humidity: 87,
        visibility: 22.93,
      },
      {
        date: "2026-03-26T12:00:00",
        weather: "light_rain",
        icon: 10,
        summary: "Light rain",
        temperature: 6.5,
        feels_like: 3.8,
        wind_chill: 4.8,
        dew_point: 2.5,
        wind: { speed: 2.4, gusts: 3.1, dir: "WNW", angle: 287 },
        cloud_cover: 99,
        pressure: 1005,
        precipitation: { total: 0.3, type: "rain" },
        probability: { precipitation: 70, storm: 0, freeze: 12 },
        ozone: 404.01,
        uv_index: 0.58,
        humidity: 75,
        visibility: 20.98,
      },
      {
        date: "2026-03-26T13:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 6.8,
        feels_like: 3.2,
        wind_chill: 4.2,
        dew_point: 2.2,
        wind: { speed: 3, gusts: 3.7, dir: "WNW", angle: 303 },
        cloud_cover: 100,
        pressure: 1005,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 56, storm: 0, freeze: 12 },
        ozone: 402.36,
        uv_index: 0.61,
        humidity: 72,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T14:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7.2,
        feels_like: 3.8,
        wind_chill: 5.2,
        dew_point: 1.5,
        wind: { speed: 2.7, gusts: 3.7, dir: "WNW", angle: 296 },
        cloud_cover: 100,
        pressure: 1006,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 40, storm: 0, freeze: 11 },
        ozone: 401.6,
        uv_index: 0.76,
        humidity: 66,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T15:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7.2,
        feels_like: 4.5,
        wind_chill: 5.5,
        dew_point: 1.2,
        wind: { speed: 2.2, gusts: 3.6, dir: "WNW", angle: 295 },
        cloud_cover: 100,
        pressure: 1006,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 40, storm: 0, freeze: 11 },
        ozone: 400.52,
        uv_index: 0.56,
        humidity: 65,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T16:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7.2,
        feels_like: 4.2,
        wind_chill: 5.2,
        dew_point: 1,
        wind: { speed: 2.7, gusts: 3.8, dir: "WNW", angle: 300 },
        cloud_cover: 100,
        pressure: 1007,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 45, storm: 0, freeze: 11 },
        ozone: 398.09,
        uv_index: 0.34,
        humidity: 64,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T17:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 7,
        feels_like: 3.8,
        wind_chill: 5.2,
        dew_point: 0.8,
        wind: { speed: 2.4, gusts: 3.6, dir: "NW", angle: 304 },
        cloud_cover: 100,
        pressure: 1007,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 39, storm: 0, freeze: 12 },
        ozone: 396.23,
        uv_index: 0.17,
        humidity: 64,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T18:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 6.2,
        feels_like: 3,
        wind_chill: 5,
        dew_point: 0.8,
        wind: { speed: 2.1, gusts: 3.4, dir: "NW", angle: 312 },
        cloud_cover: 100,
        pressure: 1008,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 32, storm: 0, freeze: 16 },
        ozone: 395.92,
        uv_index: 0,
        humidity: 67,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T19:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5.8,
        feels_like: 3,
        wind_chill: 4,
        dew_point: 0.8,
        wind: { speed: 2, gusts: 3.2, dir: "NNW", angle: 327 },
        cloud_cover: 100,
        pressure: 1009,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 25, storm: 0, freeze: 19 },
        ozone: 397.4,
        uv_index: 0,
        humidity: 70,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T20:00:00",
        weather: "overcast",
        icon: 7,
        summary: "Overcast",
        temperature: 5.2,
        feels_like: 2.2,
        wind_chill: 3.2,
        dew_point: 0.2,
        wind: { speed: 2, gusts: 3, dir: "NNW", angle: 344 },
        cloud_cover: 95,
        pressure: 1009,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 19, storm: 0, freeze: 23 },
        ozone: 400.43,
        uv_index: 0,
        humidity: 70,
        visibility: 24.14,
      },
      {
        date: "2026-03-26T21:00:00",
        weather: "cloudy",
        icon: 30,
        summary: "Cloudy",
        temperature: 4.8,
        feels_like: 1.8,
        wind_chill: 3.2,
        dew_point: 0,
        wind: { speed: 1.7, gusts: 2.2, dir: "NNW", angle: 338 },
        cloud_cover: 89,
        pressure: 1010,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 12, storm: 0, freeze: 26 },
        ozone: 402.62,
        uv_index: 0,
        humidity: 71,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T22:00:00",
        weather: "cloudy",
        icon: 30,
        summary: "Cloudy",
        temperature: 4.2,
        feels_like: 1,
        wind_chill: 2.5,
        dew_point: -0.2,
        wind: { speed: 2, gusts: 2.7, dir: "NNW", angle: 344 },
        cloud_cover: 84,
        pressure: 1011,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 3, storm: 0, freeze: 29 },
        ozone: 406.61,
        uv_index: 0,
        humidity: 72,
        visibility: 24.13,
      },
      {
        date: "2026-03-26T23:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 3.8,
        feels_like: 0.5,
        wind_chill: 1.5,
        dew_point: -0.2,
        wind: { speed: 2.1, gusts: 2.7, dir: "NNW", angle: 344 },
        cloud_cover: 78,
        pressure: 1012,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 4, storm: 0, freeze: 33 },
        ozone: 410.27,
        uv_index: 0,
        humidity: 75,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T00:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 3.2,
        feels_like: 0.5,
        wind_chill: 1,
        dew_point: -0.2,
        wind: { speed: 2, gusts: 2.6, dir: "N", angle: 357 },
        cloud_cover: 72,
        pressure: 1012,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 3, storm: 0, freeze: 36 },
        ozone: 413.33,
        uv_index: 0,
        humidity: 77,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T01:00:00",
        weather: "mostly_cloudy",
        icon: 29,
        summary: "Mostly cloudy",
        temperature: 2.5,
        feels_like: 0.5,
        wind_chill: 0.5,
        dew_point: -1,
        wind: { speed: 2, gusts: 2.6, dir: "N", angle: 359 },
        cloud_cover: 66,
        pressure: 1013,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 41 },
        ozone: 416.1,
        uv_index: 0,
        humidity: 77,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T02:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 2.2,
        feels_like: 1,
        wind_chill: 0,
        dew_point: -1.2,
        wind: { speed: 1.8, gusts: 2.6, dir: "N", angle: 4 },
        cloud_cover: 44,
        pressure: 1013,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 2, storm: 0, freeze: 44 },
        ozone: 418.13,
        uv_index: 0,
        humidity: 77,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T03:00:00",
        weather: "partly_clear",
        icon: 28,
        summary: "Partly clear",
        temperature: 1.8,
        feels_like: -0.5,
        wind_chill: -0.5,
        dew_point: -1.8,
        wind: { speed: 1.7, gusts: 2.2, dir: "NNE", angle: 20 },
        cloud_cover: 22,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 49 },
        ozone: 420.67,
        uv_index: 0,
        humidity: 77,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T04:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 1.2,
        feels_like: -2,
        wind_chill: -1,
        dew_point: -2,
        wind: { speed: 1.6, gusts: 1.9, dir: "NNE", angle: 28 },
        cloud_cover: 0,
        pressure: 1014,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 54 },
        ozone: 422.31,
        uv_index: 0,
        humidity: 78,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T05:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 0.8,
        feels_like: -2.2,
        wind_chill: -1.2,
        dew_point: -2.2,
        wind: { speed: 1.6, gusts: 1.4, dir: "NE", angle: 39 },
        cloud_cover: 0,
        pressure: 1015,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 57 },
        ozone: 419.92,
        uv_index: 0,
        humidity: 80,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T06:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 1,
        feels_like: -2.2,
        wind_chill: -0.8,
        dew_point: -2.2,
        wind: { speed: 1.3, gusts: 1.3, dir: "NE", angle: 41 },
        cloud_cover: 0,
        pressure: 1015,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 56 },
        ozone: 415.99,
        uv_index: 0,
        humidity: 78,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T07:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 1.5,
        feels_like: -1.8,
        wind_chill: -0.2,
        dew_point: -2,
        wind: { speed: 1.3, gusts: 1.3, dir: "ENE", angle: 59 },
        cloud_cover: 0,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 53 },
        ozone: 416.52,
        uv_index: 0.13,
        humidity: 77,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T08:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 2,
        feels_like: -1,
        wind_chill: 0.5,
        dew_point: -2.8,
        wind: { speed: 1.4, gusts: 1.7, dir: "NE", angle: 49 },
        cloud_cover: 1,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 49 },
        ozone: 416.42,
        uv_index: 0.39,
        humidity: 70,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T09:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 3.8,
        feels_like: 1,
        wind_chill: 2,
        dew_point: -2.5,
        wind: { speed: 1.7, gusts: 2.8, dir: "NE", angle: 49 },
        cloud_cover: 3,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 39 },
        ozone: 417.14,
        uv_index: 0.8,
        humidity: 63,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T10:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 6,
        feels_like: 3.5,
        wind_chill: 4.5,
        dew_point: -2.2,
        wind: { speed: 1.9, gusts: 3.8, dir: "NNE", angle: 33 },
        cloud_cover: 4,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 27 },
        ozone: 418.44,
        uv_index: 1.25,
        humidity: 55,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T11:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 7.8,
        feels_like: 6.2,
        wind_chill: 6.2,
        dew_point: -1.8,
        wind: { speed: 2.1, gusts: 4.9, dir: "NNE", angle: 21 },
        cloud_cover: 3,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 18 },
        ozone: 417.86,
        uv_index: 1.41,
        humidity: 51,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T12:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 9,
        feels_like: 7.2,
        wind_chill: 8.2,
        dew_point: -1.8,
        wind: { speed: 2.1, gusts: 4.8, dir: "NNE", angle: 33 },
        cloud_cover: 1,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 11 },
        ozone: 419.75,
        uv_index: 1.73,
        humidity: 46,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T13:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 10,
        feels_like: 8.5,
        wind_chill: 9,
        dew_point: -1.8,
        wind: { speed: 2.2, gusts: 4.8, dir: "N", angle: 9 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 5 },
        ozone: 420.59,
        uv_index: 1.97,
        humidity: 43,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T14:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 10.8,
        feels_like: 9,
        wind_chill: 9.5,
        dew_point: -1.8,
        wind: { speed: 2.4, gusts: 4.8, dir: "N", angle: 356 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 1 },
        ozone: 420.3,
        uv_index: 1.47,
        humidity: 41,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T15:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 10.8,
        feels_like: 9.5,
        wind_chill: 10,
        dew_point: -2,
        wind: { speed: 2, gusts: 4.5, dir: "N", angle: 11 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 1 },
        ozone: 419.74,
        uv_index: null,
        humidity: 40,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T16:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 10.8,
        feels_like: 9.5,
        wind_chill: 10,
        dew_point: -1.8,
        wind: { speed: 2, gusts: 4.3, dir: "N", angle: 359 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 1 },
        ozone: 419.79,
        uv_index: null,
        humidity: 41,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T17:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 10.5,
        feels_like: 9.2,
        wind_chill: 9.2,
        dew_point: -1,
        wind: { speed: 2, gusts: 4.2, dir: "N", angle: 352 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 3 },
        ozone: 421.97,
        uv_index: null,
        humidity: 44,
        visibility: 24.13,
      },
      {
        date: "2026-03-27T18:00:00",
        weather: "sunny",
        icon: 2,
        summary: "Sunny",
        temperature: 8.8,
        feels_like: 8,
        wind_chill: 8,
        dew_point: 0.2,
        wind: { speed: 2, gusts: 3.4, dir: "NNW", angle: 348 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 12 },
        ozone: 424.62,
        uv_index: null,
        humidity: 55,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T19:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 6.8,
        feels_like: 5.8,
        wind_chill: 5.2,
        dew_point: -0.5,
        wind: { speed: 2, gusts: 2.7, dir: "N", angle: 358 },
        cloud_cover: 0,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 24 },
        ozone: 425.72,
        uv_index: null,
        humidity: 59,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T20:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 5.2,
        feels_like: 4,
        wind_chill: 3.5,
        dew_point: -1,
        wind: { speed: 1.9, gusts: 1.9, dir: "N", angle: 9 },
        cloud_cover: 2,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 32 },
        ozone: 425.57,
        uv_index: null,
        humidity: 64,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T21:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 4.5,
        feels_like: 3.2,
        wind_chill: 2.8,
        dew_point: -0.8,
        wind: { speed: 1.9, gusts: 2, dir: "NNE", angle: 16 },
        cloud_cover: 4,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 36 },
        ozone: 425.59,
        uv_index: null,
        humidity: 68,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T22:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 3.8,
        feels_like: 2.5,
        wind_chill: 2.5,
        dew_point: -1.2,
        wind: { speed: 1.6, gusts: 2, dir: "NE", angle: 37 },
        cloud_cover: 6,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 40 },
        ozone: 426.4,
        uv_index: null,
        humidity: 69,
        visibility: 24.14,
      },
      {
        date: "2026-03-27T23:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 3.2,
        feels_like: 2.8,
        wind_chill: 1.8,
        dew_point: -1.8,
        wind: { speed: 1.4, gusts: 2.1, dir: "NE", angle: 51 },
        cloud_cover: 4,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 43 },
        ozone: 428.55,
        uv_index: null,
        humidity: 69,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T00:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 2.5,
        feels_like: 1.8,
        wind_chill: 1.2,
        dew_point: -2,
        wind: { speed: 1.4, gusts: 2, dir: "NE", angle: 51 },
        cloud_cover: 2,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 47 },
        ozone: 424.54,
        uv_index: null,
        humidity: 72,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T01:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 2,
        feels_like: 1.5,
        wind_chill: 1,
        dew_point: -2.5,
        wind: { speed: 1.2, gusts: 1.9, dir: "NE", angle: 49 },
        cloud_cover: 0,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 50 },
        ozone: 415.6,
        uv_index: null,
        humidity: 72,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T02:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 1.5,
        feels_like: 1,
        wind_chill: 1,
        dew_point: -2.5,
        wind: { speed: 1.1, gusts: 1.8, dir: "NE", angle: 45 },
        cloud_cover: 0,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 53 },
        ozone: 411.9,
        uv_index: null,
        humidity: 74,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T03:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 1.2,
        feels_like: 0.8,
        wind_chill: 0.2,
        dew_point: -2.8,
        wind: { speed: 1, gusts: 1.7, dir: "NNE", angle: 17 },
        cloud_cover: 0,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 54 },
        ozone: 410.03,
        uv_index: null,
        humidity: 74,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T04:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 0.8,
        feels_like: 0.5,
        wind_chill: -0.5,
        dew_point: -3,
        wind: { speed: 1.1, gusts: 1.7, dir: "N", angle: 356 },
        cloud_cover: 0,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 57 },
        ozone: 411.3,
        uv_index: null,
        humidity: 75,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T05:00:00",
        weather: "clear",
        icon: 26,
        summary: "Clear",
        temperature: 0.5,
        feels_like: 0,
        wind_chill: 0,
        dew_point: -3,
        wind: { speed: 1.1, gusts: 1.6, dir: "N", angle: 5 },
        cloud_cover: 7,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 58 },
        ozone: 413.18,
        uv_index: null,
        humidity: 77,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T06:00:00",
        weather: "mostly_sunny",
        icon: 3,
        summary: "Mostly sunny",
        temperature: 0.5,
        feels_like: 0.2,
        wind_chill: -0.2,
        dew_point: -3,
        wind: { speed: 1, gusts: 1.5, dir: "NNE", angle: 14 },
        cloud_cover: 15,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 57 },
        ozone: 411.73,
        uv_index: null,
        humidity: 77,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T07:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 1,
        feels_like: 0.8,
        wind_chill: 0.8,
        dew_point: -2.5,
        wind: { speed: 0.8, gusts: 1.3, dir: "NNE", angle: 28 },
        cloud_cover: 22,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 54 },
        ozone: 409.16,
        uv_index: null,
        humidity: 77,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T08:00:00",
        weather: "cloudy",
        icon: 6,
        summary: "Cloudy",
        temperature: 2.2,
        feels_like: 2.2,
        wind_chill: 2.2,
        dew_point: -2.8,
        wind: { speed: 0.7, gusts: 1.3, dir: "NNE", angle: 26 },
        cloud_cover: 86,
        pressure: 1019,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 26, storm: 0, freeze: 40 },
        ozone: 408.26,
        uv_index: null,
        humidity: 69,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T09:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 7.8,
        feels_like: 6.8,
        wind_chill: 6.8,
        dew_point: 1.5,
        wind: { speed: 0.9, gusts: 2, dir: "N", angle: 9 },
        cloud_cover: 73,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 27, storm: 0, freeze: 11 },
        ozone: 408.15,
        uv_index: null,
        humidity: 64,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T10:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 9,
        feels_like: 6.8,
        wind_chill: 7.2,
        dew_point: 1.2,
        wind: { speed: 1.1, gusts: 2.4, dir: "N", angle: 353 },
        cloud_cover: 59,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 25, storm: 0, freeze: 5 },
        ozone: 408.04,
        uv_index: null,
        humidity: 58,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T11:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 10.2,
        feels_like: 7.2,
        wind_chill: 7.2,
        dew_point: 1.2,
        wind: { speed: 1.3, gusts: 2.8, dir: "NNW", angle: 340 },
        cloud_cover: 66,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 20, storm: 0, freeze: 0 },
        ozone: 407.93,
        uv_index: null,
        humidity: 53,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T12:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 10.2,
        feels_like: 7.8,
        wind_chill: 7.8,
        dew_point: 0.2,
        wind: { speed: 1.4, gusts: 2.9, dir: "NW", angle: 322 },
        cloud_cover: 72,
        pressure: 1018,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 12, storm: 0, freeze: 0 },
        ozone: 407.46,
        uv_index: null,
        humidity: 49,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T13:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 10.8,
        feels_like: 8.2,
        wind_chill: 8.2,
        dew_point: -0.2,
        wind: { speed: 1.6, gusts: 3.2, dir: "NW", angle: 310 },
        cloud_cover: 79,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 406.99,
        uv_index: null,
        humidity: 46,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T14:00:00",
        weather: "mostly_cloudy",
        icon: 5,
        summary: "Mostly cloudy",
        temperature: 11.2,
        feels_like: 8.5,
        wind_chill: 8.5,
        dew_point: -0.8,
        wind: { speed: 1.8, gusts: 3.4, dir: "WNW", angle: 302 },
        cloud_cover: 66,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 406.52,
        uv_index: null,
        humidity: 43,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T15:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 11.2,
        feels_like: 11.2,
        wind_chill: 11.8,
        dew_point: -0.5,
        wind: { speed: 1.9, gusts: 3.5, dir: "NW", angle: 311 },
        cloud_cover: 52,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 406.42,
        uv_index: null,
        humidity: 44,
        visibility: 24.14,
      },
      {
        date: "2026-03-28T16:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 10.8,
        feels_like: 10.5,
        wind_chill: 11,
        dew_point: -0.5,
        wind: { speed: 2.1, gusts: 3.7, dir: "NW", angle: 319 },
        cloud_cover: 39,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 406.31,
        uv_index: null,
        humidity: 45,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T17:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 10.8,
        feels_like: 10,
        wind_chill: 10.5,
        dew_point: -0.5,
        wind: { speed: 2.3, gusts: 3.9, dir: "NNW", angle: 326 },
        cloud_cover: 39,
        pressure: 1016,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 0 },
        ozone: 406.2,
        uv_index: null,
        humidity: 45,
        visibility: 24.13,
      },
      {
        date: "2026-03-28T18:00:00",
        weather: "partly_sunny",
        icon: 4,
        summary: "Partly sunny",
        temperature: 9.2,
        feels_like: 10,
        wind_chill: 10.5,
        dew_point: 0,
        wind: { speed: 2.1, gusts: 3.2, dir: "NNW", angle: 332 },
        cloud_cover: 39,
        pressure: 1017,
        precipitation: { total: 0, type: "none" },
        probability: { precipitation: 0, storm: 0, freeze: 6 },
        ozone: 404.78,
        uv_index: null,
        humidity: 52,
        visibility: 24.13,
      },
    ],
  },
};
